data:
  features_path: data/processed/features_selected.csv
  random_state: 42
  target_column: is_churned
  test_size: 0.2
  validation_enabled: true
mlflow:
  auto_register: true
  experiment_name: churn_prediction_pipeline
  production_threshold: 0.9
  staging_threshold: 0.85
models:
  lightgbm:
    enabled: true
    params:
      bagging_fraction: 0.8
      feature_fraction: 0.9
      learning_rate: 0.05
      n_estimators: 200
      num_leaves: 31
  xgboost:
    enabled: true
    params:
      colsample_bytree: 0.8
      learning_rate: 0.1
      max_depth: 6
      n_estimators: 200
      subsample: 0.8
output:
  models_dir: models
  plots_dir: plots
  reports_dir: reports
  save_artifacts: true
validation:
  data_quality_checks: true
  min_auc_threshold: 0.75
  min_precision_threshold: 0.7
  min_recall_threshold: 0.7
